### ISSUE TITLE
 iobituninstaller is limited to chinese language. At least English, Spanish, and French should be provided.

### ISSUE THREAD

**Issue by okibcn** [echoiron/echo-scoop#16]
The scoop portable version should include more languages than only Chinese. At least English, Spanish, and French should be provided from all the 39 language files provided with the portable version.

**Comment by echoiron** [comment]
Thanks for the feedback, waiting for next version of the upgrade to add

**Comment by okibcn** [comment]
I just removed the fake English lang file in the languages subfolder and everything came in English as default.

Thanks for including this package in your repo.
