### ISSUE TITLE
Request (green) PDF-XChange Editor

### ISSUE THREAD

**Issue by SiyuChen** [echoiron/echo-scoop#17]
PDF-XChange Editor is a very powerful tool for editing pdf files, which would be good to be included in the bucket. 

Would you be interested in adding it to the current bucket? 

I know a portable(green) version maintained by 423down.com is at https://www.423down.com/8466.html. But feel free to use the source you prefer.

**Comment by echoiron** [comment]
Thanks for the feedback,already supported.
Please use `scoop install echo/pdf-xchange-editor-plus` to install

**Comment by SiyuChen** [comment]
Works perfectly! Thanks
