### ISSUE TITLE
The remote server returned an error: (403) FORBIDDEN

### ISSUE THREAD

**Issue by Suyu6** [echoiron/echo-scoop#18]
![image](https://user-images.githubusercontent.com/64906597/201826990-c52d6340-0c3e-4e3d-a8d4-338a58ffdd97.png)

**Comment by echoiron** [comment]
> ![image](https://user-images.githubusercontent.com/64906597/201826990-c52d6340-0c3e-4e3d-a8d4-338a58ffdd97.png)
It should be a proxy issue or a dns resolution issue with the operator at your address
![image](https://user-images.githubusercontent.com/52339367/201832499-fa2fd26b-3cbd-4bbb-8c8d-20ca0a9ed2fb.png)

**Comment by Suyu6** [comment]
How can I solve this problem?

**Comment by echoiron** [comment]
suggest you install aria2
```bash
scoop install aria2
```

**Comment by Suyu6** [comment]
> suggest you install aria2
> 
> ```shell
> scoop install aria2
> ```

I originally installed it, and after uninstalling and reinstalling, there is still this problem

**Comment by echoiron** [comment]
try using the link to download
[download](https://xmod-my.sharepoint.cn/:u:/g/personal/admin_xmod_partner_onmschina_cn/EYfXbpeY4KFEv8bFiYvQAqwBwd3bOrGF8a250UZZTUAM7Q?download=1)

or to reinstall echo bucket
```bash
scoop bucket rm echo
scoop bucket add echo https://github.com/echoiron/echo-scoop
```

**Comment by Suyu6** [comment]
还是不行,现在QQ和百度网盘都出现了报错403  其他库没有问题  这会不会是服务器的原因

**Comment by Suyu6** [comment]
![image](https://user-images.githubusercontent.com/64906597/203236908-28a850b7-cedb-48b0-b360-dfdf7c158ee7.png)

**Comment by Suyu6** [comment]
https://github.com/ScoopInstaller/Scoop/issues/3463

https://github.com/ScoopInstaller/Scoop/issues/5035

https://github.com/ScoopInstaller/Scoop/issues/4135

Now I do not know where the problem is, my other bucket are normal, I have also replaced the physical environment and network environment have tried, there are still problems

**Comment by echoiron** [comment]
this is proxy issues, it is recommended to set a proxy
If proxy's port is 1080
- **powershell**
```
$env:HTTPS_PROXY="http://127.0.0.1:1080" ; $env:HTTP_PROXY="http://127.0.0.1:1080"
```

- **dos**
```
set http_proxy=http://127.0.0.1:1080 & set https_proxy=http://127.0.0.1:1080
```

- **linux**
```
export http_proxy="http://127.0.0.1:1080" && export https_proxy="http://127.0.0.1:1080"
```

**Comment by Suyu6** [comment]
> this is proxy issues, it is recommended to set a proxy If proxy's port is 1080
> 
> * **powershell**
> 
> ```
> $env:HTTPS_PROXY="http://127.0.0.1:1080" ; $env:HTTP_PROXY="http://127.0.0.1:1080"
> ```
> 
> * **dos**
> 
> ```
> set http_proxy=http://127.0.0.1:1080 & set https_proxy=http://127.0.0.1:1080
> ```
> 
> * **linux**
> 
> ```
> export http_proxy="http://127.0.0.1:1080" && export https_proxy="http://127.0.0.1:1080"
> ```

Still doesn't work

**Comment by Suyu6** [comment]
Still doesn't work

**Comment by Suyu6** [comment]
Modify the proxy port number, modify the proxy mode, have tried, the problem still exists

**Comment by Suyu6** [comment]
![image](https://user-images.githubusercontent.com/64906597/203778525-f4a115c9-b564-45fd-a154-65824067f7b1.png)


![image](https://user-images.githubusercontent.com/64906597/203778599-5ca5d34e-9e52-43b2-a7e3-515750ddee36.png)


![image](https://user-images.githubusercontent.com/64906597/203778659-eecf3049-f1a6-4e9d-bd1e-23e134d314f2.png)


qq  file name:
qq#9.6.9#https_xmod-my.sharepoint.cn_u_g_personal_admin_xmod_partner_onmschina_cn_EZRYo2hre0RLlUnQzypvIi0B-82OG9OMD_uy8Wkb4fFVlg_download_1_dl.7z


qqlive file name:
qqlive#11.58.5210#https_xmod-my.sharepoint.cn_u_g_personal_admin_xmod_partner_onmschina_cn_ERqw_h2f1FBPrSXLxjG1-30BomSb5uafHa5TjN4nkFo-ug_download_1_dl.7z


iobitdriverbooster file name:
iobitdriverbooster#10.1.0.86#https_xmod-my.sharepoint.cn_u_g_personal_admin_xmod_partner_onmschina_cn_ERhy9oRfwy9BmMPKakYnvqwBC49q_0HzL50yjqnsTeUpTA_download=1#dl.7z


Download the 7z archive via your browser
Change the file name against the url
PowerShell
scoop update
Update successfully

**Comment by Suyu6** [comment]
But it is so troublesome to change the file name like this
Still haven't found where the problem is
Could it be a problem with scoop?
