### ISSUE TITLE
Add mobaxterm

### ISSUE THREAD

**Issue by Suyu6** [echoiron/echo-scoop#20]
Can you add a Chinese version of mobaxterm?

https://github.com/RipplePiam/MobaXterm-Chinese-Simplified

**Comment by echoiron** [comment]
mobaxterm has been added, but it is not the latest version, if there is a latest green version, I will add it first.
```bash
scoop install echo/mobaxterm
```

**Comment by Suyu6** [comment]
> 

ok,thanks
