### ISSUE TITLE
add request

### ISSUE THREAD

**Issue by Suyu6** [echoiron/echo-scoop#23]
k-lite-codec-pack-full-np:
https://codecguide.com/download_kl.htm
https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/k-lite-codec-pack-full-np.json

XySubFilter-with-libass:
https://github.com/Masaiki/xy-VSFilter/releases
https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/xysubfilter-libass-np.json

**Comment by echoiron** [comment]
the official scoop already exists, so there is no need to add it again
