### ISSUE TITLE
iqiyi

### ISSUE THREAD

**Issue by Suyu6** [echoiron/echo-scoop#26]
爱奇艺绿化处理脚本内容路径有问题
每次绿化完后桌面快捷方式图标都找不到文件
应该是爱奇艺客户端文件名字有变化导致的
请求修复绿化脚本
因为好几个版本都是这种情况，每次都需要手动去编辑快捷图标位置或者绿化脚本内容
所以请求更新，这样后续版本可以直接使用

**Comment by echoiron** [comment]
IQIYIClient.exe改名为QyClient.exe导致，绿化脚本已更新
