### ISSUE TITLE
Foobar 2k 2.1.2 汉化版推荐

### ISSUE THREAD

**Issue by Fvr9W** [echoiron/echo-scoop#27]
地址：https://www.esnpc.com/foobar2000-20-simplified-chinese-version/
用于替代 Asion 的版本
Asion 也在网站上推荐了这个版本

**Comment by echoiron** [comment]
> 地址：https://www.esnpc.com/foobar2000-20-simplified-chinese-version/ 用于替代 Asion 的版本 Asion 也在网站上推荐了这个版本

两者差别不大，后期可做备用
