### ISSUE TITLE
腾讯会议安装后无法启动

### ISSUE THREAD

**Issue by KochabStar** [echoiron/echo-scoop#31]
"Rename-Item \"$dir\\`$_10_\" \"$dir\\$version\"",
这个有问题，我看现在应该是$_22_

**Comment by echoiron** [comment]
> "Rename-Item "$dir\`$_10_" "$dir\$version"", 这个有问题，我看现在应该是$_22_

已更新，请使用`scoop uninstall tencentmeeting -p`命令强制卸载，然后使用`scoop install echo/tencentmeeting`命令进行安装
