### ISSUE TITLE
idm@6.42.20: decompress error

### ISSUE THREAD

**Issue by SiyuChen** [echoiron/echo-scoop#32]
Updating one outdated app:
Updating 'idm' (6.41.3 -> 6.42.20)
Downloading new version
Loading dl.7z from cache.
WARN  Warning: No hash in manifest. SHA256 for 'idm#6.42.20#https_xmod-my.sharepoint.cn_u_g_personal_admin_xmod_partner_onmschina_cn_EWnKTL6_oJdKvH03Tl-n30YBRpXhlGPAiyHMVjfScM12pA_download_1_dl.7z' is:
    aa89c4dc17a8f2beec6149cf93e33ec3d81e3fcf09db26736d26983d50420ad3
Uninstalling 'idm' (6.41.3)
Installing 'idm' (6.42.20) [64bit] from 'echo' bucket
Loading dl.7z from cache.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Siyu\scoop\apps\idm\6.42.20\dl.7z.
Log file:
  ~\scoop\apps\idm\6.42.20\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/echoiron/echo-scoop/issues/new?title=idm%406.42.20%3a+decompress+error

**Comment by echoiron** [comment]
> Updating one outdated app: Updating 'idm' (6.41.3 -> 6.42.20) Downloading new version Loading dl.7z from cache. WARN Warning: No hash in manifest. SHA256 for 'idm#6.42.20#https_xmod-my.sharepoint.cn_u_g_personal_admin_xmod_partner_onmschina_cn_EWnKTL6_oJdKvH03Tl-n30YBRpXhlGPAiyHMVjfScM12pA_download_1_dl.7z' is: aa89c4dc17a8f2beec6149cf93e33ec3d81e3fcf09db26736d26983d50420ad3 Uninstalling 'idm' (6.41.3) Installing 'idm' (6.42.20) [64bit] from 'echo' bucket Loading dl.7z from cache. Extracting dl.7z ... ERROR Exit code was 2! Failed to extract files from C:\Users\Siyu\scoop\apps\idm\6.42.20\dl.7z. Log file: ~\scoop\apps\idm\6.42.20\7zip.log
> 
> Please try again or create a new issue by using the following link and paste your console output: https://github.com/echoiron/echo-scoop/issues/new?title=idm%406.42.20%3a+decompress+error

```bash
scoop install echo/idm
```

```log
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'idm' (6.42.20) [64bit] from 'echo' bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 990ad6|OK  |   2.2MiB/s|D:/scoop/cache/idm#6.42.20#f7e0684.7z
Download: Status Legend:
Download: (OK):download completed.
WARN  Warning: No hash in manifest. SHA256 for 'idm#6.42.20#f7e0684.7z' is:
    aa89c4dc17a8f2beec6149cf93e33ec3d81e3fcf09db26736d26983d50420ad3
Extracting dl.7z ... done.
Linking D:\scoop\apps\idm\current => D:\scoop\apps\idm\6.42.20
Creating shortcut for IDMan (IDMan.exe)
'idm' (6.42.20) was installed successfully!
```
