### ISSUE TITLE
IDM待更新

### ISSUE THREAD

**Issue by Jiang10086** [echoiron/echo-scoop#34]
官网已经到了6.42.26.1版本
https://mirror2.internetdownloadmanager.com/idman642build26.exe?v=lt&filename=idman642build26.exe

**Comment by echoiron** [comment]
> 官网已经到了6.42.26.1版本 https://mirror2.internetdownloadmanager.com/idman642build26.exe?v=lt&filename=idman642build26.exe

更新了
