### ISSUE TITLE
acmekit@3.1: decompress error

### ISSUE THREAD

**Issue by sszq** [echoiron/echo-scoop#4]
## 安装报错，老铁帮忙看下
Installing 'acmekit' (3.1) [64bit]
Loading AcmeKit_v3.1.exe from cache
WARN  Warning: No hash in manifest. SHA256 for 'dl.7z' is:
    5ba3948ce7bfa72106f2cc41d155c796293314627d9388b8d3b61d008a34bf12
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from D:\scoop\apps\acmekit\3.1\dl.7z.
Log file:
  D:\scoop\apps\acmekit\3.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/echoiron/echo-scoop/issues/new?title=acmekit%403.1%3a+decompress+error

**Comment by echoiron** [comment]
> ## 安装报错，老铁帮忙看下
> Installing 'acmekit' (3.1) [64bit]
> Loading AcmeKit_v3.1.exe from cache
> WARN Warning: No hash in manifest. SHA256 for 'dl.7z' is:
> 5ba3948ce7bfa72106f2cc41d155c796293314627d9388b8d3b61d008a34bf12
> Extracting dl.7z ... ERROR Exit code was 2!
> Failed to extract files from D:\scoop\apps\acmekit\3.1\dl.7z.
> Log file:
> D:\scoop\apps\acmekit\3.1\7zip.log
> 
> Please try again or create a new issue by using the following link and paste your console output:
> https://github.com/echoiron/echo-scoop/issues/new?title=acmekit%403.1%3a+decompress+error

更新了一版，再试试看
