### ISSUE TITLE
QQ request update

### ISSUE THREAD

**Issue by Suyu6** [echoiron/echo-scoop#9]
dreamcast Update link：https://wwa.lanzoui.com/b385621    Password:6666

**Comment by echoiron** [comment]
> dreamcast Update link：https://wwa.lanzoui.com/b385621 Password:6666

谢谢反馈，已更新

**Comment by Suyu6** [comment]
> > dreamcast 更新链接：https://wwa.lanzoui.com/b385621 密 码：6666
> 
> 谢谢反馈，已更新

foobar 2k asion 蓝奏：https://wwi.lanzoup.com/b0jitwwf 密码:fb2k 更新了
FB_1.6.11_Asion_20220524102545.exe
